# Generated by Django 4.2.25 on 2025-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ecdh_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
