# Generated by Django 4.2.25 on 2025-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile_ecdh_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
