# Generated by Django 4.2.25 on 2025-10-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='session_id',
        ),
    ]
